swagger: '2.0'
info:
  title: iReceptorPlus Statistics API
  version: 1.0.0
  contact:
    name: iReceptor Plus
    url: 'https://www.ireceptorplus.org'
    email: info@ireceptorplus.org
  description: >
    Statistics API for iReceptor Plus repositories.
basePath: /irplus/v1/stats

schemes:
  - https
  - http
produces:
  - application/json
consumes:
  - application/x-www-form-urlencoded
  - application/json
tags:
  - name: info
    description: Service information
  - name: clones
    description: Statistics API for clones
  - name: rearrangements
    description: Statistics API for rearrangements

definitions:
  # Info object
  info_object:
    type: object
    description: Provides information about the API response
    properties:
      title:
        type: string
      version:
        type: string
      description:
        type: string
      contact: 
        type: object
        properties:
          name:
            type: string
          url:
            type: string
          email:
            type: string

  junction_length_response:
    type: object
    properties:
      Info:
        $ref: '#/definitions/info_object'
      Stats:
        type: array
        description: >
            Array of junction length stats objects, entry for each repertoire_id, data_processing_id, and
            sample_processing_id requested
        items:
          type: object
          properties:
            repertoire_id:
              type: string
              description: The repertoire_id for this set of stats.
              example: REPID_4598
            sample_processing_id:
              type: string
              description: The sample_processing_id for this set of stats.
              example: SPID_1
            data_processing_id:
              type: string
              description: The data_processing_id for this set of stats.
              example: DPID_1
            junction_lengths:
              type: array
              example: [{"junction_length":15, "count":14890},{"junction_length":16, "count":50693}]
              description: >
                  Array containing the junction length stats. Each array element contains a junction_length
                  and the count for that junction_length in the given repertoire.
              items: 
                type: object
                properties:
                  junction_length:
                    type: integer
                    description: The junction_length
                  count:
                    type: integer
                    description: The count for this junction_length

          
  # The response object /rearrangement endpoint
  gene_usage_response:
    type: object
    properties:
      Info:
        $ref: '#/definitions/info_object'
      Stats:
        type: array
        description: Array of gene stats objects, one per repertoire
        items:
          type: object
          properties:
            repertoire_id:
              type: string
              description: The repertoire_id for this set of stats.
              example: REPID_4598
            sample_processing_id:
              type: string
              description: The sample_processing_id for this set of stats.
              example: SPID_1
            data_processing_id:
              type: string
              description: The data_processing_id for this set of stats.
              example: DPID_1
            total:
              type: integer
              description: Total number of elements found in the repertoire.
              example: 30
            fields:
              type: array
              description: Array of fields the stats were performed on in the repertoire.
              items:
                type: object
                properties:
                  field:
                    type: string
                    description: >
                        The field that the statistics data refers to. This should be an AIRR compliant field
                        that exists in the repository.
                    example: v_gene
                  data:
                    type: array
                    description: Array of responses for each of the fields requested.
                    example: [{"name":"IGHV1", "count":5}, {"name":"IGHV2", "count":12}, {"name":"IGHV3", "count":13}]
                    items:
                      type: object
                      properties:
                        name:
                          type: string
                          description: The name of the gene component
                        count: 
                          type: integer
                          description: The number of times that the gene component was found.

# error response
  error_response:
    type: object
    properties:
      message:
        type: string
        description: Detail about the error



paths:
  /:
    x-swagger-router-controller: status
    get:
      description: |
        Service heartbeat.
      consumes:
        - application/octet-stream
      operationId: getStatus
      responses:
        '200':
          description: |
            Success.
          schema:
            type: object
            properties:
              result:
                type: string

  /info:
    x-swagger-router-controller: status
    get:
      description: |
        Service information.
      tags:
        - info
      consumes:
        - application/octet-stream
      operationId: getInfo
      responses:
        '200':
          description: |
            Success.
          schema:
            type: object
            properties:
              name:
                type: string
              version:
                type: string

  /swagger:
    x-swagger-pipe: swagger_raw

  /rearrangement/junction_length:
    x-swagger-router-controller: rearrangement
    post:
      description: >
        Perform a junction length distribution analysis for the rearrangements that
        belong to the specified repertoire_id (and/or sample_processing_id and data_processing_id).
      tags:
        - rearrangements
      parameters:
        - in: body
          name: data
          schema:
            type: object
            properties:
              repertoires:
                type: array
                description: Array of repertoires to perform the statistics on.
                items:
                  type: object
                  properties:
                    repertoire_id:
                      type: string
                      description: The reperotire ID on which to perform the analysis
                    sample_processing_id:
                      type: string
                      description: The sample processing ID within the repertoire on which to perform the analysis
                    data_processing_id:
                      type: string
                      description: >
                        The data processing ID on which to perform the analysis.
                        If this is not provided and there is more than one data processing entity attached to 
                        the repertoire then the primary_annotation is used if one exists. If there is more than
                        one data processing entity and there is no primary annotation, then this is an error, as
                        it is ambigous as to which data processing to use.
      operationId: rearrangementJunctionLengthDistribution
      responses:
        '200':
          description: >
            A successful call returns a JSON description of the requested junction length distribution
          schema:
            $ref: '#/definitions/junction_length_response'
        '400':
          description: Invalid request
          schema:
            $ref: '#/definitions/error_response'
        '500':
          description: Server error
          schema:
            $ref: '#/definitions/error_response'

  /rearrangement/gene_usage:
    x-swagger-router-controller: rearrangement
    post:
      description: >
        Perform a gene usage analysis for the rearrangementes that belong to the specified repertoire (and/or sample_processing and data_processing entity).
      tags:
        - rearrangements
      parameters:
        - in: body
          name: data
          schema:
            type: object
            properties:
              fields:
                type: array
                items:
                  type: string
                  enum:
                    - v_subgroup
                    - v_gene
                    - v_call
                    - d_subgroup
                    - d_gene
                    - d_call
                    - j_subgroup
                    - j_gene
                    - j_call
                    - c_subgroup
                    - c_gene
                    - c_call
                description: The types of gene usage stats requested (one of V,D, or J subgroup, gene, or allele)
                example:
                  - v_gene
                  - d_call
              repertoires:
                type: array
                description: Array of repertoires to perform the statistics on.
                items:
                  type: object
                  properties:
                    repertoire_id:
                      type: string
                      description: The reperotire ID on which to perform the analysis
                      example: REPID_4598
                    sample_processing_id:
                      type: string
                      description: The sample_processing_id on which to perform the analysis
                      example: SPID_1
                    data_processing_id:
                      type: string
                      description: >
                        The data processing ID on which to perform the analysis.
                        If this is not provided and there is more than one data processing entity attached to 
                        the repertoire then the primary_annotation is used if one exists. If there is more than
                        one data processing entity and there is no primary annotation, then this is an error, as
                        it is ambigous as to which data processing to use.
                      example: DPID_1
      operationId: rearrangementGeneUsage
      responses:
        '200':
          description: >
            A successful call returns a JSON description of the requested gene usage distribution 
          schema:
            $ref: '#/definitions/gene_usage_response'
        '400':
          description: Invalid request
          schema:
            $ref: '#/definitions/error_response'
        '500':
          description: Server error
          schema:
            $ref: '#/definitions/error_response'
            
  /clone/junction_length:
    x-swagger-router-controller: clone
    post:
      description: >
        Perform a junction length distribution analysis for the rearrangements that belong to the specified repertoire (and/or sample_processing and data processing entity).
      tags:
        - clones
      parameters:
        - in: body
          name: data
          schema:
            type: object
            properties:
              repertoire_id:
                type: string
              sample_processing_id:
                type: string
              data_processing_id:
                type: string
              clone_processing_id:
                type: string
      operationId: cloneJunctionLengthDistribution
      responses:
        '200':
          description: >
            A successful call returns a JSON description of the requested junction length distribution 
          schema:
            $ref: '#/definitions/junction_length_response'
        '400':
          description: Invalid request
          schema:
            $ref: '#/definitions/error_response'
        '500':
          description: Server error
          schema:
            $ref: '#/definitions/error_response'

  /clone/gene_usage:
    x-swagger-router-controller: clone
    post:
      description: >
        Perform a gene usage analysis for the clones that belong to the specified repertoire (and/or sample_processing and data_processing entity).
      tags:
        - clones
      parameters:
        - in: body
          name: data
          schema:
            type: object
            properties:
              repertoire_id:
                type: string
              sample_processing_id:
                type: string
              data_processing_id:
                type: string
              clone_processing_id:
                type: string
      operationId: cloneGeneUsage
      responses:
        '200':
          description: >
            A successful call returns a JSON description of the requested gene usage distribution 
          schema:
            $ref: '#/definitions/gene_usage_response'
        '400':
          description: Invalid request
          schema:
            $ref: '#/definitions/error_response'
        '500':
          description: Server error
          schema:
            $ref: '#/definitions/error_response'
