swagger: '2.0'
info:
  title: iReceptorPlus Statistics API
  version: 1.0.0
  contact:
    name: iReceptor Plus
    url: 'https://www.ireceptorplus.org'
    email: info@ireceptorplus.org
  description: >
    Statistics API for iReceptor Plus repositories.
basePath: /irplus/v1/stats

schemes:
  - https
  - http
produces:
  - application/json
consumes:
  - application/x-www-form-urlencoded
  - application/json
tags:
  - name: info
    description: Service information
  - name: clones
    description: Statistics API for clones
  - name: rearrangements
    description: Statistics API for rearrangements

definitions:
  # Info object
  info_object:
    type: object
    description: Provides information about the API response
    properties:
      title:
        type: string
      version:
        type: string
      description:
        type: string
      contact: 
        type: object
        properties:
          name:
            type: string
          url:
            type: string
          email:
            type: string

  junction_length_response:
    type: object
    properties:
      Info:
        $ref: '#/definitions/info_object'
      junction_length:
        type: array
        items: 
          type: object
          properties:
            value:
              type: string
            count:
              type: integer
          
  # The response object /rearrangement endpoint
  gene_usage_response:
    type: object
    properties:
      Info:
        $ref: '#/definitions/info_object'
      total:
        type: integer
        description: Total number of element found
      family:
        type: array
        description: Array of key/value pairs, one per gene family found.
        items:
          family_name: 
            type: integer
            description: A key value pair: key is the gene family name, value is the count for how many times that gene name was found.
      gene:
        type: array
        description: Array of key/value pairs, one per gene found.
        items: 
          gene_name: 
            type: integer
            description: A key value pair: key is the gene name, value is the count for how many times that gene was found.
      allele:
        type: array
        description: Array of key/value pairs, one per allele found.
        items: 
          allele_name: 
            type: integer
            description: A key value pair: key is the allele name, value is the count for how many times that allele was found.

# error response
  error_response:
    type: object
    properties:
      message:
        type: string
        description: Detail about the error



paths:
  /:
    x-swagger-router-controller: status
    get:
      description: |
        Service heartbeat.
      consumes:
        - application/octet-stream
      operationId: getStatus
      responses:
        '200':
          description: |
            Success.
          schema:
            type: object
            properties:
              result:
                type: string

  /info:
    x-swagger-router-controller: status
    get:
      description: |
        Service information.
      tags:
        - info
      consumes:
        - application/octet-stream
      operationId: getInfo
      responses:
        '200':
          description: |
            Success.
          schema:
            type: object
            properties:
              name:
                type: string
              version:
                type: string

  /swagger:
    x-swagger-pipe: swagger_raw

  /rearrangement/junction_length:
    x-swagger-router-controller: rearrangement
    post:
      description: >
        Perform a junction length distribution analysis for the rearrangements that belong to the specified repertoire (and/or sample_processing and data processing entity).
      tags:
        - rearrangements
      parameters:
        - in: body
          name: data
          schema:
            type: object
            properties:
              repertoire_id:
                type: string
              sample_processing_id:
                type: string
              data_processing_id:
                type: string
      operationId: rearrangementJunctionLengthDistribution
      responses:
        '200':
          description: >
            A successful call returns a JSON description of the requested junction length distribution
          schema:
            $ref: '#/definitions/junction_length_response'
        '400':
          description: Invalid request
          schema:
            $ref: '#/definitions/error_response'
        '500':
          description: Server error
          schema:
            $ref: '#/definitions/error_response'

  /rearrangement/gene_usage:
    x-swagger-router-controller: rearrangement
    post:
      description: >
        Perform a gene usage analysis for the rearrangementes that belong to the specified repertoire (and/or sample_processing and data_processing entity).
      tags:
        - rearrangements
      parameters:
        - in: body
          name: data
          schema:
            type: object
            properties:
              repertoire_id:
                type: string
              sample_processing_id:
                type: string
              data_processing_id:
                type: string
      operationId: rearrangementGeneUsage
      responses:
        '200':
          description: >
            A successful call returns a JSON description of the requested gene usage distribution 
          schema:
            $ref: '#/definitions/gene_usage_response'
        '400':
          description: Invalid request
          schema:
            $ref: '#/definitions/error_response'
        '500':
          description: Server error
          schema:
            $ref: '#/definitions/error_response'
            
  /clone/junction_length:
    x-swagger-router-controller: clone
    post:
      description: >
        Perform a junction length distribution analysis for the rearrangements that belong to the specified repertoire (and/or sample_processing and data processing entity).
      tags:
        - clones
      parameters:
        - in: body
          name: data
          schema:
            type: object
            properties:
              repertoire_id:
                type: string
              sample_processing_id:
                type: string
              data_processing_id:
                type: string
              clone_processing_id:
                type: string
      operationId: cloneJunctionLengthDistribution
      responses:
        '200':
          description: >
            A successful call returns a JSON description of the requested junction length distribution 
          schema:
            $ref: '#/definitions/junction_length_response'
        '400':
          description: Invalid request
          schema:
            $ref: '#/definitions/error_response'
        '500':
          description: Server error
          schema:
            $ref: '#/definitions/error_response'

  /clone/gene_usage:
    x-swagger-router-controller: clone
    post:
      description: >
        Perform a gene usage analysis for the clones that belong to the specified repertoire (and/or sample_processing and data_processing entity).
      tags:
        - clones
      parameters:
        - in: body
          name: data
          schema:
            type: object
            properties:
              repertoire_id:
                type: string
              sample_processing_id:
                type: string
              data_processing_id:
                type: string
              clone_processing_id:
                type: string
      operationId: cloneGeneUsage
      responses:
        '200':
          description: >
            A successful call returns a JSON description of the requested gene usage distribution 
          schema:
            $ref: '#/definitions/gene_usage_response'
        '400':
          description: Invalid request
          schema:
            $ref: '#/definitions/error_response'
        '500':
          description: Server error
          schema:
            $ref: '#/definitions/error_response'
